### ISSUE TITLE
Error: Could not find the include file "dataProtectionScript"

### ISSUE THREAD

**Issue by gcoskun** [vocol/vocol#114]
When I start vocol the first time and configure it,  get the following error:

WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
/home/project/vocol/helper/tools/owl2vowl
mkdir: path already exists: ../evolution
SingleVoc.nt is copied to evolution
/home/project/vocol/helper/tools/owl2vowl
GET //startup 302 10917.605 ms - 48
Errors file is generated

Error: Could not find the include file "dataProtectionScript"
    at getIncludePath (/home/project/vocol/node_modules/ejs/lib/ejs.js:162:13)
    at includeSource (/home/project/vocol/node_modules/ejs/lib/ejs.js:306:17)
    at /home/project/vocol/node_modules/ejs/lib/ejs.js:702:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/home/project/vocol/node_modules/ejs/lib/ejs.js:678:15)
    at includeSource (/home/project/vocol/node_modules/ejs/lib/ejs.js:310:9)
    at /home/project/vocol/node_modules/ejs/lib/ejs.js:702:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/home/project/vocol/node_modules/ejs/lib/ejs.js:678:15)
    at Template.compile (/home/project/vocol/node_modules/ejs/lib/ejs.js:557:12)
GET // 500 91.309 ms - 1025
[2019-01-31 08:44:48] Server     INFO  Dataset: in-memory: load file: ../serializations/SingleVoc.nt
[2019-01-31 08:44:48] Server     INFO  Running in read-only mode for /dataset
[2019-01-31 08:44:48] Server     INFO  Apache Jena Fuseki 3.8.0
[2019-01-31 08:44:48] Config     INFO  FUSEKI_HOME=/home/project/vocol/helper/tools/apache-jena-fuseki
[2019-01-31 08:44:48] Config     INFO  FUSEKI_BASE=/home/project/vocol/helper/tools/apache-jena-fuseki/run
[2019-01-31 08:44:48] Config     INFO  Shiro file: file:///home/project/vocol/helper/tools/apache-jena-fuseki/run/shiro.ini
[2019-01-31 08:44:49] Config     INFO  Register: /dataset
[2019-01-31 08:44:49] Server     INFO  Started 2019/01/31 08:44:49 UTC on port 3030

**Comment by lavdim** [comment]
@ahemaid , thanks for updating it. I think this process should be documented, and it should be possible that VoCol can work with an empty data protection script.

**Comment by ahemaid** [comment]
I handle this in the new vocol version. I also have updated the docker image so please update us if you still have a problem.
