### ISSUE TITLE
queries for the "home" section leads to status code 502

### ISSUE THREAD

**Issue by gcoskun** [vocol/vocol#116]
whenever I start vocol and navigate to the "home" section the communication with FUSEKI leads to status code 502

I modified the code a bit to catch ths error. the console looks like this

> vocol@0.0.1 start /home/project/vocol
> node ./bin/www "80" "3030"

VoCol server is running on port 80
Jena Fuseki server is running on port 3030
                     USER        PID ACCESS COMMAND
3030/tcp:            root      F.... java
  7285sending sparql query
 PREFIX owl: <http://www.w3.org/2002/07/owl#>       SELECT ?p ?o      WHERE {      ?s a owl:Ontology.      OPTIONAL { ?s ?p ?o.}}

##### returned status code equals 502

Error: SparQL query failed.
    at module.exports.responseHandler (/home/project/vocol/node_modules/sparql-client/lib/client.js:51:17)
    at Request.requestCallback [as _callback] (/home/project/vocol/node_modules/sparql-client/lib/client.js:111:29)
    at Request.self.callback (/home/project/vocol/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/project/vocol/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/project/vocol/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
sending sparql query
 PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>       PREFIX owl: <http://www.w3.org/2002/07/owl#>       PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>      SELECT       (count(?cls) as ?Classes)      (count(?rdfProperty) as ?RDF_Property)      (count(?objProp) as ?OWL_ObjectProperty)       (count(?dtProp) as ?OWL_DatatypeProperty)       (count(?annot) as ?OWL_AnnotationProperty)      (count(?indiv) as ?Individuals)      WHERE {{?objProp a owl:ObjectProperty.}       UNION {?dtProp a owl:DatatypeProperty.}      UNION {?indiv a owl:NamedIndividual.}       UNION {?annot a owl:AnnotationProperty.}       UNION {?cls a rdfs:Class. FILTER(!isBlank(?cls))}       UNION {?cls a owl:Class. FILTER(!isBlank(?cls))} 	    UNION {?rdfProperty a rdf:Property.}	  	  }

##### returned status code equals 502

Error: SparQL query failed.
    at module.exports.responseHandler (/home/project/vocol/node_modules/sparql-client/lib/client.js:51:17)
    at Request.requestCallback [as _callback] (/home/project/vocol/node_modules/sparql-client/lib/client.js:111:29)
    at Request.self.callback (/home/project/vocol/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/project/vocol/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/project/vocol/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by ahemaid** [comment]
I am not sure which is going here, 
just check if fuseki is running on port 3030
and  try to give **npm install** command to ensure that all required libs are installed or give **npm install sparql-client** , and update me about the current status

**Comment by gcoskun** [comment]
the "query" tab works and I can see the fuseki interface and can also copy paste the sparql query which causes the error and it works. But it does not work when I navigate to the "home" tab. The metadata elements in the "home" tab which send these queries cause this error.

**Comment by ahemaid** [comment]
I handle this in the new vocol version. I also have updated the docker image so please update us if you still have a problem.
