### ISSUE TITLE
Provide a Dockerfile

### ISSUE THREAD

**Issue by skarampatakis** [vocol/vocol#78]
Hi,
it seems that there is a docker image published https://hub.docker.com/r/lavdim/vocol/, but it seems to be outdated. 

Could you provide a Dockerfile so I could rebuild VoCol locally?

Or else could you give some info about how I could update the current image using a custom Dockerfile?

Thank you.

**Comment by ahemaid** [comment]
Hi, 
Please follow the new docker image at https://hub.docker.com/r/ahemid/newvocol/.
There you are providing the latest version of VoCol.

Thanks.

**Comment by skarampatakis** [comment]
Hi @ahemaid,

I updated the image according to your suggestions. I am using docker-compose to bring the whole beast up. So I have this Dockerfile

```
FROM ahemid/newvocol:latest

COPY ./start.sh /start.sh

CMD ["/bin/sh", "/start.sh"]
```

and start.sh is
```
cd home/project/vocol
npm install
sh helper/scripts/resetApp.sh
npm start
```
I added npm install because the first time I brought up the server, the vocol container complained the missing node_modules folder. 

On my .yml configuration file I have 
```
vocol:
        build: ./vocol
        ports:
            - "8087:80"
```

So in sort, the vocol container builds and it is up. The first time I access it, it redirects to /config where I give the configuration parameters. After I finish I click on "Save" but after a while I have an "unable to connect" page. So I check and it seems that the container has exited. I check the logs and have this.

```

> bcrypt@1.0.3 install /home/project/vocol/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/home/project/vocol/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> semantic-ui@2.2.14 install /home/project/vocol/node_modules/semantic-ui
> gulp install

[11:34:58] Using gulpfile /home/project/vocol/node_modules/semantic-ui/gulpfile.js
[11:34:58] Starting 'install'...
Cannot locate files to update at path:  /home/project/vocol/semantic\/src/definitions

Running installer
[11:34:58] Starting 'run setup'...
? It looks like you have a semantic.json file already. (Use arrow keys)
❯ Yes, extend my current settings. 
npm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! semantic-ui@2.2.14 install: `gulp install`
npm ERR! Exit status 130
npm ERR! 
npm ERR! Failed at the semantic-ui@2.2.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-16T11_35_05_557Z-debug.log
  Skip install 
> vocol@0.0.1 start /home/project/vocol
> node ./bin/www

Express server listening on port 80
GET / 302 11.836 ms - 60
GET /config 200 9.310 ms - 12756
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap-theme.min.css 200 4.063 ms - 23409
GET /stylesheets/style.css 200 4.819 ms - 2932
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.css 200 5.388 ms - 146010
GET /javascripts/bower_components/jquery/dist/jquery.min.js 200 5.013 ms - 86659
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.min.css 200 3.880 ms - 121200
GET /semantic/dist/semantic.min.css 200 3.597 ms - 593653
GET /javascripts/config.js 200 1.428 ms - 1635
GET /javascripts/bower_components/bootstrap/dist/js/bootstrap.min.js 200 1.536 ms - 37045
GET /semantic/dist/semantic.min.js 200 1.397 ms - 282771
GET /ckeditor/ckeditor.js 200 1.406 ms - 560314
GET /semantic/dist/themes/default/assets/fonts/icons.woff2 200 0.475 ms - 77160
GET /ckeditor/config.js?t=H8DA 200 0.450 ms - 1412
GET /ckeditor/skins/kama/editor.css?t=H8DA 200 0.963 ms - 25835
GET /ckeditor/lang/en.js?t=H8DA 200 0.881 ms - 11046
GET /ckeditor/styles.js?t=H8DA 200 0.490 ms - 5546
GET /ckeditor/plugins/confighelper/plugin.js?t=H8DA 200 0.486 ms - 10112
GET /ckeditor/plugins/scayt/dialogs/dialog.css 200 0.813 ms - 419
GET /ckeditor/plugins/tableselection/styles/tableselection.css 200 0.905 ms - 1082
GET /ckeditor/skins/kama/icons.png?t=dee99e2 200 0.450 ms - 6196
GET /ckeditor/contents.css?t=H8DA 200 0.892 ms - 2955
GET /ckeditor/plugins/tableselection/styles/tableselection.css 200 0.800 ms - 1082
POST /config 200 14.448 ms - 1495
SyntaxError: /home/project/vocol/jsonDataFiles/userConfigurations.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/project/vocol/node_modules/jsonfile/index.js:33:18
    at /home/project/vocol/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.css 200 1.020 ms - 146010
GET /javascripts/bower_components/bootstrap/dist/js/bootstrap.min.js 200 2.690 ms - 37045
GET /stylesheets/style.css 200 5.577 ms - 2932
GET /javascripts/bower_components/jquery/dist/jquery.min.js 200 2.699 ms - 86659
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.min.css 200 2.759 ms - 121200
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap-theme.min.css 200 6.305 ms - 23409
GET /semantic/dist/semantic.min.css 200 6.186 ms - 593653
GET /semantic/dist/semantic.min.js 200 0.844 ms - 282771
/home/project/vocol/app.js:97
        callback(loginUserName);
        ^

TypeError: callback is not a function
    at /home/project/vocol/app.js:97:9
    at /home/project/vocol/node_modules/jsonfile/index.js:43:5
    at /home/project/vocol/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vocol@0.0.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vocol@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-16T11_36_46_249Z-debug.log

> semantic-ui@2.2.14 install /home/project/vocol/node_modules/semantic-ui
> gulp install

[11:38:30] Using gulpfile /home/project/vocol/node_modules/semantic-ui/gulpfile.js
[11:38:30] Starting 'install'...

Running installer
Cannot locate files to update at path:  /home/project/vocol/semantic\/src/definitions
[11:38:30] Starting 'run setup'...
? It looks like you have a semantic.json file already. (Use arrow keys)
❯ Yes, extend my current settings. 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! semantic-ui@2.2.14 install: `gulp install`
npm ERR! Exit status 130
npm ERR! 
npm ERR! Failed at the semantic-ui@2.2.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-16T11_38_37_597Z-debug.log
  Skip install 
> vocol@0.0.1 start /home/project/vocol
> node ./bin/www

Express server listening on port 80
GET / 302 12.568 ms - 60
GET /config 200 8.425 ms - 12756
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.css 200 3.093 ms - 146010
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.min.css 200 0.764 ms - 121200
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap-theme.min.css 200 1.256 ms - 23409
GET /stylesheets/style.css 200 1.108 ms - 2932
GET /javascripts/bower_components/bootstrap/dist/js/bootstrap.min.js 200 1.160 ms - 37045
GET /javascripts/bower_components/jquery/dist/jquery.min.js 200 1.110 ms - 86659
GET /semantic/dist/semantic.min.css 200 1.164 ms - 593653
GET /javascripts/config.js 200 1.737 ms - 1635
GET /semantic/dist/semantic.min.js 200 1.900 ms - 282771
GET /ckeditor/ckeditor.js 200 1.176 ms - 560314
GET /semantic/dist/themes/default/assets/fonts/icons.woff2 200 0.568 ms - 77160
GET /ckeditor/config.js?t=H8DA 200 0.448 ms - 1412
GET /ckeditor/skins/kama/editor.css?t=H8DA 200 0.600 ms - 25835
GET /ckeditor/lang/en.js?t=H8DA 200 0.523 ms - 11046
GET /ckeditor/styles.js?t=H8DA 200 0.443 ms - 5546
GET /ckeditor/plugins/confighelper/plugin.js?t=H8DA 200 0.486 ms - 10112
GET /ckeditor/plugins/scayt/dialogs/dialog.css 200 0.900 ms - 419
GET /ckeditor/plugins/tableselection/styles/tableselection.css 200 0.821 ms - 1082
GET /ckeditor/skins/kama/icons.png?t=dee99e2 200 0.457 ms - 6196
GET /ckeditor/contents.css?t=H8DA 200 0.834 ms - 2955
GET /ckeditor/plugins/tableselection/styles/tableselection.css 200 0.897 ms - 1082
GET / 302 1.150 ms - 60
GET /config 200 2.785 ms - 12756
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.css 200 0.482 ms - 146010
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.min.css 200 1.551 ms - 121200
GET /stylesheets/style.css 200 2.155 ms - 2932
GET /javascripts/bower_components/jquery/dist/jquery.min.js 200 2.208 ms - 86659
GET /javascripts/bower_components/bootstrap/dist/js/bootstrap.min.js 200 2.022 ms - 37045
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap-theme.min.css 200 2.056 ms - 23409
GET /javascripts/config.js 200 1.436 ms - 1635
GET /semantic/dist/semantic.min.js 200 1.721 ms - 282771
GET /semantic/dist/semantic.min.css 200 2.282 ms - 593653
GET /ckeditor/ckeditor.js 200 1.662 ms - 560314
GET /semantic/dist/themes/default/assets/fonts/icons.woff2 200 0.577 ms - 77160
GET /ckeditor/config.js?t=H8DA 200 0.608 ms - 1412
GET /ckeditor/skins/kama/editor.css?t=H8DA 200 0.790 ms - 25835
GET /ckeditor/lang/en.js?t=H8DA 200 0.816 ms - 11046
GET /ckeditor/styles.js?t=H8DA 200 0.433 ms - 5546
GET /ckeditor/plugins/confighelper/plugin.js?t=H8DA 200 0.515 ms - 10112
GET /ckeditor/plugins/scayt/dialogs/dialog.css 200 0.735 ms - 419
GET /ckeditor/plugins/tableselection/styles/tableselection.css 200 0.778 ms - 1082
GET /ckeditor/skins/kama/icons.png?t=dee99e2 200 0.451 ms - 6196
GET /ckeditor/contents.css?t=H8DA 200 0.438 ms - 2955
GET /ckeditor/plugins/tableselection/styles/tableselection.css 200 0.332 ms - 1082
POST /config 200 13.525 ms - 1495
SyntaxError: /home/project/vocol/jsonDataFiles/userConfigurations.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/project/vocol/node_modules/jsonfile/index.js:33:18
    at /home/project/vocol/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
GET /stylesheets/style.css 200 2.992 ms - 2932
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap-theme.min.css 200 5.162 ms - 23409
GET /javascripts/bower_components/jquery/dist/jquery.min.js 200 3.522 ms - 86659
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.css 200 3.376 ms - 146010
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.min.css 200 3.866 ms - 121200
GET /javascripts/bower_components/bootstrap/dist/js/bootstrap.min.js 200 4.673 ms - 37045
GET /semantic/dist/semantic.min.js 200 5.752 ms - 282771
GET /semantic/dist/semantic.min.css 200 3.414 ms - 593653
/home/project/vocol/app.js:97
        callback(loginUserName);
        ^

TypeError: callback is not a function
    at /home/project/vocol/app.js:97:9
    at /home/project/vocol/node_modules/jsonfile/index.js:43:5
    at /home/project/vocol/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vocol@0.0.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vocol@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-16T11_39_52_029Z-debug.log

> semantic-ui@2.2.14 install /home/project/vocol/node_modules/semantic-ui
> gulp install

[11:41:01] Using gulpfile /home/project/vocol/node_modules/semantic-ui/gulpfile.js
[11:41:01] Starting 'install'...
Cannot locate files to update at path:  /home/project/vocol/semantic\/src/definitions

Running installer
[11:41:01] Starting 'run setup'...
? It looks like you have a semantic.json file already. (Use arrow keys)
❯ Yes, extend my current settings. 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! semantic-ui@2.2.14 install: `gulp install`
npm ERR! Exit status 130
npm ERR! 
npm ERR! Failed at the semantic-ui@2.2.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-16T11_41_09_130Z-debug.log
  Skip install 
> vocol@0.0.1 start /home/project/vocol
> node ./bin/www

Express server listening on port 80
```

When I restart the container and attach to it running a bash shell, I check the folder of the app and it seems that the /home/project/vocol/jsonDataFiles/userConfigurations.json does not exist. 

Am I doing something wrong?

**Comment by skarampatakis** [comment]
So, I removed sh helper/scripts/resetApp.sh from the start.sh script. 
Then added a userConfigurations.json file which I copy to /home/project/vocol/jsonDataFiles/userConfigurations.json. Vocol then starts successfully. However I still cannot see my repo in editor.
